/usr/lib/python3/dist-packages/PIL/Image.py:968: UserWarning: Palette images with Transparency   expressed in bytes should be converted to RGBA images
  ' expressed in bytes should be converted ' +
Met Get status get failed - random number generator or Internet not avail?
*** Error in Met Status: (<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='datapoint.metoffice.gov.uk', port=80): Max retries exceeded with url: /public/data/val/wxfcs/all/json/324151?res=daily&key=ad54d79a-8c73-4e53-a86e-e0a27216a0d6 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb2ef1fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))")), <traceback object at 0xb2ea8878>)
